<a href="https://colab.research.google.com/github/roshika1235/Data_Analysis_Tasks/blob/main/NUMPY_TASK.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np

## Part 1: Creating and Reshaping Arrays


1. Create Arrays:
o Create two NumPy arrays:


In [5]:
#  A 1D array of 10 equally spaced values between 0 and 50.
b=np.linspace(0,50,10)


In [6]:
# A 2D array of shape (3x3) containing random integers between 5 and 20.
a=np.random.randint(5,20,9)
a.reshape(3,3)


array([[15, 11, 11],
       [ 8,  7, 14],
       [ 5, 18, 18]])

 2. Array Dimensions:

In [7]:
# Print the dimensions of both arrays.
print(a.ndim)
print(b.ndim)


1
1


In [16]:
# Print the shape of both arrays
print(a.shape)
print(b.shape)

(9,)
(2, 5)


3. Reshaping:

In [9]:
# Reshape the 1D array into a 2D array with shape (2x5)
# Print the reshaped array.
# Flatten the reshaped array back to 1D and print it.
ar1=np.arange(1,100,10)
ar1
print(ar1.reshape(2,5))
print(ar1.reshape(-1))

[[ 1 11 21 31 41]
 [51 61 71 81 91]]
[ 1 11 21 31 41 51 61 71 81 91]


## Part 2: Indexing and Slicing
4. Indexing:

In [10]:
# For the 2D array created in Part 1, print the element present at the 2nd row and 3rd column.
b=ar1.reshape(2,5)
print(b)
print(b[1,2])

[[ 1 11 21 31 41]
 [51 61 71 81 91]]
71


In [11]:
# Extract the first two rows and the last two columns of the array.
print(b[:2,-2:])

[[31 41]
 [81 91]]


5. Slicing

In [18]:
# Slice the first four elements from the flattened 1D array.
ar1[:4]
#Reverse the elements of the 1D array using slicing.
ar1[::-1]

array([91, 81, 71, 61, 51, 41, 31, 21, 11,  1])

# Part 3: Array Operations

6. Array Arithmetic:


In [12]:
# Create another 1D array of 10 integers between 1 and 10.
# Perform the following element-wise operations between the 1D
# arrays created in Part 1 and Part 3:
# ▪ Addition
# ▪ Multiplication
# ▪ Subtract a constant value (e.g., 5) from the array.

b_reshaped = b.reshape(2, 5)
c = np.arange(1, 11).reshape(2, 5)
print(b_reshaped * c)
print(b_reshaped+c)
print(b_reshaped-5)

[[  1  22  63 124 205]
 [306 427 568 729 910]]
[[  2  13  24  35  46]
 [ 57  68  79  90 101]]
[[-4  6 16 26 36]
 [46 56 66 76 86]]


## Part 4: Random Number Generation and Copying

In [13]:
# Create a 1D array of 5 random values between 0 and 1.
# Create another 1D array of 5 random values between -1 and 1.
d=np.random.rand(5)
d
e=np.random.randn(5)
e

array([-1.24171195, -0.51335493,  0.51059384, -0.37954389,  0.79613813])

## Part 5: Bonus


In [14]:

#  Challenge Task:
# o Write a program that asks the user to input a number (n), and then
# generates an n x n array of random integers between 1 and 100.
# o Find the sum of all the elements in the array and print the result.
n=int(input())
dim1=np.random.randint(1,100,n*n)
print(dim1)
f=dim1.reshape(n,n)
print(f)
print(sum(f))

5
[81 77 43 66 46 51 72 65  8  8  4 27 46 74 31 47 34  5 42 92 16 90 89 43
 71]
[[81 77 43 66 46]
 [51 72 65  8  8]
 [ 4 27 46 74 31]
 [47 34  5 42 92]
 [16 90 89 43 71]]
[199 300 248 233 248]
